# Generated by Django 5.0.1 on 2024-01-10 16:56

import django.db.models.deletion
import entry.customs.current_date
import entry.customs.nanoid
import pgvector.django
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.CharField(default=entry.customs.nanoid.generate_nanoid, editable=False, max_length=21, primary_key=True, serialize=False)),
                ('title', models.CharField(default=entry.customs.current_date.current_datatime, editable=False, max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntryEmbedding',
            fields=[
                ('embedding', pgvector.django.VectorField(dimensions=1024)),
                ('text', models.CharField(blank=True, null=True)),
                ('id', models.CharField(default=entry.customs.nanoid.generate_nanoid, editable=False, max_length=21, primary_key=True, serialize=False)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.entry')),
            ],
        ),
    ]
